// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.1
// 	protoc        v3.6.1
// source: clairvoyant.proto

package gonest

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ClairvoyantMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Role   string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *ClairvoyantMessage) Reset() {
	*x = ClairvoyantMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clairvoyant_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClairvoyantMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClairvoyantMessage) ProtoMessage() {}

func (x *ClairvoyantMessage) ProtoReflect() protoreflect.Message {
	mi := &file_clairvoyant_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClairvoyantMessage.ProtoReflect.Descriptor instead.
func (*ClairvoyantMessage) Descriptor() ([]byte, []int) {
	return file_clairvoyant_proto_rawDescGZIP(), []int{0}
}

func (x *ClairvoyantMessage) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ClairvoyantMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_clairvoyant_proto protoreflect.FileDescriptor

var file_clairvoyant_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6c, 0x61, 0x69, 0x72, 0x76, 0x6f, 0x79, 0x61, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x67, 0x6f, 0x6e, 0x65, 0x73, 0x74, 0x22, 0x40, 0x0a, 0x12, 0x43,
	0x6c, 0x61, 0x69, 0x72, 0x76, 0x6f, 0x79, 0x61, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x42, 0x08, 0x5a,
	0x06, 0x67, 0x6f, 0x6e, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clairvoyant_proto_rawDescOnce sync.Once
	file_clairvoyant_proto_rawDescData = file_clairvoyant_proto_rawDesc
)

func file_clairvoyant_proto_rawDescGZIP() []byte {
	file_clairvoyant_proto_rawDescOnce.Do(func() {
		file_clairvoyant_proto_rawDescData = protoimpl.X.CompressGZIP(file_clairvoyant_proto_rawDescData)
	})
	return file_clairvoyant_proto_rawDescData
}

var file_clairvoyant_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_clairvoyant_proto_goTypes = []interface{}{
	(*ClairvoyantMessage)(nil), // 0: gonest.ClairvoyantMessage
}
var file_clairvoyant_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clairvoyant_proto_init() }
func file_clairvoyant_proto_init() {
	if File_clairvoyant_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_clairvoyant_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClairvoyantMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clairvoyant_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clairvoyant_proto_goTypes,
		DependencyIndexes: file_clairvoyant_proto_depIdxs,
		MessageInfos:      file_clairvoyant_proto_msgTypes,
	}.Build()
	File_clairvoyant_proto = out.File
	file_clairvoyant_proto_rawDesc = nil
	file_clairvoyant_proto_goTypes = nil
	file_clairvoyant_proto_depIdxs = nil
}
