// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.1
// 	protoc        v3.6.1
// source: humanvote.proto

package gonest

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type HumanVoteMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *HumanVoteMessage) Reset() {
	*x = HumanVoteMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_humanvote_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumanVoteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanVoteMessage) ProtoMessage() {}

func (x *HumanVoteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_humanvote_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanVoteMessage.ProtoReflect.Descriptor instead.
func (*HumanVoteMessage) Descriptor() ([]byte, []int) {
	return file_humanvote_proto_rawDescGZIP(), []int{0}
}

func (x *HumanVoteMessage) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

var File_humanvote_proto protoreflect.FileDescriptor

var file_humanvote_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x68, 0x75, 0x6d, 0x61, 0x6e, 0x76, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x67, 0x6f, 0x6e, 0x65, 0x73, 0x74, 0x22, 0x2a, 0x0a, 0x10, 0x48, 0x75, 0x6d,
	0x61, 0x6e, 0x56, 0x6f, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x42, 0x08, 0x5a, 0x06, 0x67, 0x6f, 0x6e, 0x65, 0x73, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_humanvote_proto_rawDescOnce sync.Once
	file_humanvote_proto_rawDescData = file_humanvote_proto_rawDesc
)

func file_humanvote_proto_rawDescGZIP() []byte {
	file_humanvote_proto_rawDescOnce.Do(func() {
		file_humanvote_proto_rawDescData = protoimpl.X.CompressGZIP(file_humanvote_proto_rawDescData)
	})
	return file_humanvote_proto_rawDescData
}

var file_humanvote_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_humanvote_proto_goTypes = []interface{}{
	(*HumanVoteMessage)(nil), // 0: gonest.HumanVoteMessage
}
var file_humanvote_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_humanvote_proto_init() }
func file_humanvote_proto_init() {
	if File_humanvote_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_humanvote_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumanVoteMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_humanvote_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_humanvote_proto_goTypes,
		DependencyIndexes: file_humanvote_proto_depIdxs,
		MessageInfos:      file_humanvote_proto_msgTypes,
	}.Build()
	File_humanvote_proto = out.File
	file_humanvote_proto_rawDesc = nil
	file_humanvote_proto_goTypes = nil
	file_humanvote_proto_depIdxs = nil
}
