// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.1
// 	protoc        v3.6.1
// source: roledistribution.proto

package gonest

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//Enum listant tout les roles possibles.
type Role int32

const (
	Role_HUMANROLE       Role = 0
	Role_WEREWOLFROLE    Role = 1
	Role_WITCHROLE       Role = 2
	Role_CUPIDROLE       Role = 3
	Role_HUNTERROLE      Role = 4
	Role_CLAIRVOYANTROLE Role = 5
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "HUMANROLE",
		1: "WEREWOLFROLE",
		2: "WITCHROLE",
		3: "CUPIDROLE",
		4: "HUNTERROLE",
		5: "CLAIRVOYANTROLE",
	}
	Role_value = map[string]int32{
		"HUMANROLE":       0,
		"WEREWOLFROLE":    1,
		"WITCHROLE":       2,
		"CUPIDROLE":       3,
		"HUNTERROLE":      4,
		"CLAIRVOYANTROLE": 5,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_roledistribution_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_roledistribution_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_roledistribution_proto_rawDescGZIP(), []int{0}
}

//Le leader utilise ce message pour assigner à chaque joueur son role.
type RoleDistributionMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Role   Role   `protobuf:"varint,2,opt,name=role,proto3,enum=gonest.Role" json:"role,omitempty"`
}

func (x *RoleDistributionMessage) Reset() {
	*x = RoleDistributionMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roledistribution_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleDistributionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleDistributionMessage) ProtoMessage() {}

func (x *RoleDistributionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_roledistribution_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleDistributionMessage.ProtoReflect.Descriptor instead.
func (*RoleDistributionMessage) Descriptor() ([]byte, []int) {
	return file_roledistribution_proto_rawDescGZIP(), []int{0}
}

func (x *RoleDistributionMessage) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RoleDistributionMessage) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_HUMANROLE
}

var File_roledistribution_proto protoreflect.FileDescriptor

var file_roledistribution_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x6f, 0x6c, 0x65, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x67, 0x6f, 0x6e, 0x65, 0x73, 0x74,
	0x22, 0x53, 0x0a, 0x17, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x12, 0x20, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0c, 0x2e, 0x67, 0x6f, 0x6e, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52,
	0x04, 0x72, 0x6f, 0x6c, 0x65, 0x2a, 0x6a, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0d, 0x0a,
	0x09, 0x48, 0x55, 0x4d, 0x41, 0x4e, 0x52, 0x4f, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c,
	0x57, 0x45, 0x52, 0x45, 0x57, 0x4f, 0x4c, 0x46, 0x52, 0x4f, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0d,
	0x0a, 0x09, 0x57, 0x49, 0x54, 0x43, 0x48, 0x52, 0x4f, 0x4c, 0x45, 0x10, 0x02, 0x12, 0x0d, 0x0a,
	0x09, 0x43, 0x55, 0x50, 0x49, 0x44, 0x52, 0x4f, 0x4c, 0x45, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a,
	0x48, 0x55, 0x4e, 0x54, 0x45, 0x52, 0x52, 0x4f, 0x4c, 0x45, 0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f,
	0x43, 0x4c, 0x41, 0x49, 0x52, 0x56, 0x4f, 0x59, 0x41, 0x4e, 0x54, 0x52, 0x4f, 0x4c, 0x45, 0x10,
	0x05, 0x42, 0x08, 0x5a, 0x06, 0x67, 0x6f, 0x6e, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_roledistribution_proto_rawDescOnce sync.Once
	file_roledistribution_proto_rawDescData = file_roledistribution_proto_rawDesc
)

func file_roledistribution_proto_rawDescGZIP() []byte {
	file_roledistribution_proto_rawDescOnce.Do(func() {
		file_roledistribution_proto_rawDescData = protoimpl.X.CompressGZIP(file_roledistribution_proto_rawDescData)
	})
	return file_roledistribution_proto_rawDescData
}

var file_roledistribution_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_roledistribution_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_roledistribution_proto_goTypes = []interface{}{
	(Role)(0),                       // 0: gonest.Role
	(*RoleDistributionMessage)(nil), // 1: gonest.RoleDistributionMessage
}
var file_roledistribution_proto_depIdxs = []int32{
	0, // 0: gonest.RoleDistributionMessage.role:type_name -> gonest.Role
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_roledistribution_proto_init() }
func file_roledistribution_proto_init() {
	if File_roledistribution_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_roledistribution_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleDistributionMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_roledistribution_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_roledistribution_proto_goTypes,
		DependencyIndexes: file_roledistribution_proto_depIdxs,
		EnumInfos:         file_roledistribution_proto_enumTypes,
		MessageInfos:      file_roledistribution_proto_msgTypes,
	}.Build()
	File_roledistribution_proto = out.File
	file_roledistribution_proto_rawDesc = nil
	file_roledistribution_proto_goTypes = nil
	file_roledistribution_proto_depIdxs = nil
}
